knpu_oauth2_client:
    clients:
        github:
            type: github
            client_id: '%env(GITHUB_CLIENT_ID)%'
            client_secret: '%env(GITHUB_CLIENT_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: github

        facebook:
            type: facebook
            client_id: '%env(FACEBOOK_CLIENT_ID)%'
            client_secret: '%env(FACEBOOK_CLIENT_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: facebook
            graph_api_version: v2.12
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: google

        instagram:
            type: instagram
            client_id: '%env(INSTAGRAM_CLIENT_ID)%'
            client_secret: '%env(INSTAGRAM_CLIENT_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: instagram
